### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by liaqataliazad1** [simonfarah/tiktok-bot#123] opened 2024-05-24 10:10 UTC
File "C:\Users\kHaN\python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kHaN\python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable

**Comment by simonfarah** [comment] 2024-08-26 06:34
You must have chosen a service that was marked as offline. Please only choose services marked as online. If the error was caused by a cloudflare page, track the issue here #114

**Closed by simonfarah** 2024-08-26 06:34 UTC
